Added configurability for cluster name
Azure/cyclecloud-slurm-workspace pull request #85
Opened 2024-08-07 17:17 UTC by abatallas

2024-08-09 20:51 UTC, bwatrous approved these changes

2024-08-12 14:32 UTC, ryanhamel requested changes
We need to either support cluster names with spaces and other characters, or restrict it with the regex.

2024-08-12 14:33 UTC, ryanhamel commented on uidefinitions/createUiDefinition.json
> +                "regex": "^.{3,}$",
This regex should also be set in the bicep params

2024-08-13 15:23 UTC, ryanhamel approved these changes

2024-08-13 15:23 UTC, merged